name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
   call-reusable-workflow:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        uses: ./.github/workflows/reusable-workflow.yml

        with:
          node: 14

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
